# Generated by Django 4.1.6 on 2023-05-11 15:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numberPassengers",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "totalAvailable",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberAvailableEconomy",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberAvailableBuisness",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberAvailableFirtsClass",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("departureDate", models.DateField(default=datetime.date(2023, 5, 11))),
                ("arrivalDate", models.DateField(default=datetime.date(2023, 5, 11))),
                (
                    "departureTime",
                    models.TimeField(default=datetime.time(15, 54, 31, 32195)),
                ),
                (
                    "arrivalTime",
                    models.TimeField(default=datetime.time(15, 54, 31, 32195)),
                ),
                ("flightDuration", models.TimeField(default=datetime.time(0, 0))),
                ("airline", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airport", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numberOfEconomy",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberOfBusiness",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberOfFirstClass",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EconomyPrice", models.DecimalField(decimal_places=2, max_digits=7)),
                ("BusinessPrice", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "FirstClassPrice",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numberOfEconomy",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberOfBusiness",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "numberOfFirstClass",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("timeStarted", models.DateTimeField()),
                ("confirmedStatus", models.BooleanField(default=False)),
                (
                    "flightID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.flight"
                    ),
                ),
                (
                    "passengerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.passenger",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="endLocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_location",
                to="project.location",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="planeID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.plane"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="priceID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.price",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="startLocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_location",
                to="project.location",
            ),
        ),
    ]
